version: '3.8'

services:
  spring-boot-app:
    container_name: spring-boot-app-container
    build:
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    container_name: postgres-test
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=expenses_app_dev
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
          - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local